In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
path='/content/iris.data'

#task-1 IRIS FLOWER CLASSIFICATION

#Import libraries

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

#Reading iris dataset

In [4]:
df=pd.read_csv("/content/Iris.csv.xls")
df=pd.DataFrame(df)

#Analysing the dataset

In [5]:
print(df.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [7]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [8]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

#Features

In [9]:
X = df.drop(columns=["Id", "Species"])

In [10]:
Y = df["Species"]

#Splitting into training and testing

In [11]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

#Creation and training the model

In [12]:
model=RandomForestClassifier(n_estimators=100,random_state=42)
model.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

#Predicting and outcomes

In [13]:
Y_pred = model.predict(X_test)
print(Y_pred)

['Iris-versicolor' 'Iris-setosa' 'Iris-virginica' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-setosa' 'Iris-versicolor' 'Iris-virginica'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-virginica' 'Iris-versicolor' 'Iris-versicolor' 'Iris-virginica'
 'Iris-setosa' 'Iris-virginica' 'Iris-setosa' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-setosa' 'Iris-setosa']

In [14]:
sample=[[7.2,3.0,5.8,1.8]]
prediction = model.predict(sample)
print('predicted Species:',prediction)

predicted Species: ['Iris-virginica']

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

#Evaluting the model

#*Accuracy*

In [15]:
accuracy = accuracy_score(Y_test,Y_pred)

In [16]:
print(accuracy)

1.0

#Confusion matrix

In [17]:
print(confusion_matrix(Y_test,Y_pred))

[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

#Classification report

In [18]:
report = classification_report(Y_test,Y_pred,output_dict=True)
report_df=pd.DataFrame(report).transpose()
report_df=report_df.round(2)
print(report_df)

                 precision  recall  f1-score  support
Iris-setosa            1.0     1.0       1.0     10.0
Iris-versicolor        1.0     1.0       1.0      9.0
Iris-virginica         1.0     1.0       1.0     11.0
accuracy               1.0     1.0       1.0      1.0
macro avg              1.0     1.0       1.0     30.0
weighted avg           1.0     1.0       1.0     30.0